### ISSUE TITLE
VOLUME_CAPACITY parameter does not get applied (7.4 & 7.5) 

### ISSUE THREAD

**Issue by therevills** [jboss-container-images/jboss-amq-7-broker-openshift-image#54]
In the template the VOLUME_CAPACITY parameter does not get applied for persistence-ssl:

https://raw.githubusercontent.com/jboss-container-images/jboss-amq-7-broker-openshift-image/74-7.4.0.GA/templates/amq-broker-74-persistence-ssl.yaml

```
    volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: ${APPLICATION_NAME}-amq-pvol
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi  
```
