### ISSUE TITLE
AMQ_GLOBAL_MAX_SIZE description and default value don't match

### ISSUE THREAD

**Issue by tux-o-matic** [jboss-container-images/jboss-amq-7-broker-openshift-image#63]
The description for the ```AMQ_GLOBAL_MAX_SIZE``` ENV describe a default that is way too high and not the one actually applied. ```GLOBAL_MAX_SIZE```is the right parameter, in its absence, half the Xmx will be et as max global size.
```yaml
- description: "Maximum amount of memory which message data may consume (Default: Undefined, half of the system's memory)."
  displayName: AMQ Global Max Size
  name: AMQ_GLOBAL_MAX_SIZE
  value: 100 gb
```
This oddity is still present in the [7.7 template](https://github.com/jboss-container-images/jboss-amq-7-broker-openshift-image/blob/amq-broker-77-dev/templates/amq-broker-77-basic.yaml#L233).
